sudo: required
services:
  - docker

before_install:
  - docker build -t rosslen/frontend_web -f Dockerfile.dev .

script:
  - docker run rosslen/frontend_web npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "rosa_docker_webapp"
  env: "RosaDockerWebapp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-207398959169"
  bucket_path: "rosa_docker_webapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

